name: Test
on:
  push:
    paths:
      - 'test-cluster/**'
    branches:
      - main
#   schedule:
#     # The "*" (#42, asterisk) character has special semantics in YAML, so this
#     # string has to be quoted.
#     - cron: '0/15 * * * *'
env:
  tf_actions_working_dir: test-cluster

jobs:
  test:
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup private repo credentials for private modules
        run: git config --global url."https://oauth2:${{ secrets.TF_TOKEN }}@github.com".insteadOf ssh://git@github.com
        shell: sh

      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Execute Tests
        run: ./run_tests.sh
        shell: sh
        env: 
          TF_DIR: ${{ github.workspace }}/${{ env.tf_actions_working_dir }}

      - name: Debug
        run: kubectl describe pods
        if: always()
